name: Release Plugin

on:
  workflow_call:
    inputs:
      file:
        type: string
        required: true
      sourcepawn-version:
        type: string
        default: "1.11"
        required: false

    secrets:
      token:
        required: true

jobs:
  release:
    name: Release Plugin (SourcePawn ${{ inputs.sourcepawn-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SourcePawn ${{ inputs.sourcepawn-version }}
        uses: KatsuteTF/Workflows/actions/setup-sourcepawn@main

      - name: Format Name
        env:
          sp: ${{ inputs.file }}
        run: echo "smx=${sp//.sp/.smx}" >> $GITHUB_ENV

      - name: Compile ${{ inputs.file }}
        run: spcomp "${{ inputs.file }}" -o "${{ env.smx }}"

      - name: Deploy to GitHub Releases
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ${{ env.smx }}
          repo-token: ${{ secrets.token }}