name: spcomp
description: SourceMod compiler
inputs:
  sourcemod-version:
    description: SourceMod version to compile with
    required: false
    default: "1.11"
runs:
  using: composite
  steps:
    - name: Install SourceMod ${{ inputs.sourcemod-version }}
      uses: rumblefrog/setup-sp@v1.2.4
      with:
        version: ${{ inputs.sourcemod-version }}